
deploymentName: votingserver-deployment
deploymentLabel: votingserver

replicaCount: 1

image:
  repository: fabricatic/votingserver
  tag: latest

containerPort: 8090

service:
  type: LoadBalancer
  port: 8090
  targetPort: 8090

config_enabled: true
profile_enabled: true
eureka_enabled: true