version: "3.8"

services:

  postgres:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    networks:
      - backend

  keycloak:
    depends_on:
      - postgres
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    container_name: local_keycloak
    image: jboss/keycloak:13.0.0
    ports:
      - "7080:8080"
    restart: unless-stopped
    networks:
      - backend


  configserver:
    image: fabricatic/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
    
   
  eurekaserver:
    image: fabricatic/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
     - backend
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      
  votingserver:
    image: fabricatic/votingserver:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - backend
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
  
  gatewayserver:
    image: fabricatic/gatewayserver:latest
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - backend
    depends_on:
      - configserver
      - eurekaserver
      - votingserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    
networks:
  backend: