version: "3.8"

services:

  # zipkin:
  #   image: openzipkin/zipkin
  #   mem_limit: 700m
  #   ports:
  #     - "9411:9411"
  #   networks:
  #    - backend

  configserver:
    image: fabricatic/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
   
  eurekaserver:
    image: fabricatic/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
     - backend
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      
  votingserver:
    image: fabricatic/votingserver:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - backend
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
  
  votingserver2:
    image: fabricatic/votingserver:latest
    mem_limit: 700m
    ports:
      - "8091:8091"
    networks:
      - backend
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    
  votingserver3:
    image: fabricatic/votingserver:latest
    mem_limit: 700m
    ports:
      - "8092:8092"
    networks:
      - backend
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
  
  gatewayserver:
    image: fabricatic/gatewayserver:latest
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - backend
    depends_on:
      - configserver
      - eurekaserver
      - votingserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    
networks:
  backend: